name: mExport
version: 0.0.1
author: Aman Singh

default-extensions:
  - BangPatterns
  - DeriveFunctor
  - DeriveGeneric
  - DuplicateRecordFields
  - FlexibleContexts
  - LambdaCase
  - OverloadedStrings
  - RecordWildCards
  - TemplateHaskell
  - TypeApplications
  - ViewPatterns
  - NamedFieldPuns

ghc-options:
  - -O2
  - -j4
  - -Wall
  - -Wredundant-constraints
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -ddump-minimal-imports

library:
  source-dirs: lib
  dependencies:
    - base
    - bytestring
    - containers
    - Cabal
    - directory
    - filepath
    - ghc-lib-parser
    - lens
    - pretty
    - process
    - text
    - unordered-containers

executables:
  mexport:
    main: Main.hs
    source-dirs: src
    dependencies:
      - base
      - directory
      - filepath
      - mExport
      - optparse-applicative
      - text
      - yaml

tests:
  mexport-test:
    main: Main.hs
    source-dirs: test
    dependencies:
      - base
      - hspec
      - mExport
      - pretty-simple
      - text
      - unordered-containers
