name: mExport
version: 0.0.1
author: Aman Singh

default-extensions:
  - BangPatterns
  - DeriveFunctor
  - DeriveGeneric
  - DuplicateRecordFields
  - LambdaCase
  - OverloadedStrings
  - TypeApplications
  - TemplateHaskell
  - ViewPatterns

library:
  source-dirs: lib
  ghc-options:
    - -O2
    - -j4
    - -Wall
  dependencies:
    - base
    - directory
    - filepath
    - ghc-lib-parser
    - haskell-names
    - haskell-src-exts
    - lens
    - text
    - unordered-containers

executables:
  mexport:
    main: Main.hs
    source-dirs: src
    ghc-options:
      - -O2
      - -j4
      - -Wall
    dependencies:
      - base
      - mExport
      - optparse-applicative

tests:
  mexport-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
      - -Wall
    dependencies:
      - base
      - hspec
      - mExport
      - pretty-simple
      - text
      - unordered-containers
