name: mExport
version: 0.0.1
author: Aman Singh

default-extensions:
  - BangPatterns
  - DeriveFunctor
  - DeriveGeneric
  - DuplicateRecordFields
  - OverloadedStrings
  - TypeApplications
  - LambdaCase

library:
  source-dirs: src
  ghc-options:
    - -O2
    - -j4
    - -Wall
  dependencies:
    - base
    - directory
    - filepath
    - haskell-names
    - haskell-src-exts
    - optparse-applicative
    - text
    - unordered-containers

executables:
  mexport:
    main: Main.hs
    source-dirs: src
    ghc-options:
      - -O2
      - -j4
      - -Wall
    dependencies:
      - base
      - directory
      - filepath
      - haskell-names
      - haskell-src-exts
      - optparse-applicative
      - text
      - unordered-containers

tests:
  mexport-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
      - -Wall
    dependencies:
      - base
      - hspec
      - mExport
      - text
      - unordered-containers
